import hashlib
import json
import sqlite3
from collections.abc import Generator
from datetime import datetime
from pathlib import Path

from sqlalchemy import Connection, Engine, create_engine, event, text
from sqlalchemy.orm import Session, sessionmaker

from northstar.core.config import get_settings

sqlite3.register_adapter(datetime, lambda value: value.isoformat())


def _connect_args(url: str) -> dict[str, object]:
    if url.startswith("sqlite"):
        return {"check_same_thread": False, "timeout": 30}
    return {}


settings = get_settings()
engine_options: dict[str, object] = {
    "connect_args": _connect_args(settings.database_url),
    "pool_pre_ping": True,
}
if not settings.database_url.startswith("sqlite"):
    engine_options.update(
        pool_size=settings.database_pool_size,
        max_overflow=settings.database_max_overflow,
        pool_recycle=1800,
    )
engine: Engine = create_engine(settings.database_url, **engine_options)
SessionLocal = sessionmaker(bind=engine, autoflush=False, expire_on_commit=False)


@event.listens_for(engine, "connect")
def configure_sqlite(connection: object, _record: object) -> None:
    if not settings.database_url.startswith("sqlite"):
        return
    cursor = connection.cursor()
    cursor.execute("PRAGMA foreign_keys=ON")
    cursor.execute("PRAGMA journal_mode=WAL")
    cursor.execute("PRAGMA synchronous=NORMAL")
    cursor.execute("PRAGMA busy_timeout=30000")
    cursor.close()


def get_db() -> Generator[Session]:
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def initialize_database() -> None:
    migrations = Path(__file__).resolve().parents[2] / "migrations"
    with engine.begin() as connection:
        if connection.dialect.name == "postgresql":
            connection.execute(text("SELECT pg_advisory_xact_lock(734921847)"))
        connection.exec_driver_sql(
            "CREATE TABLE IF NOT EXISTS python_migrations "
            "(name VARCHAR(255) PRIMARY KEY, applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)"
        )
        applied = {
            row[0]
            for row in connection.exec_driver_sql("SELECT name FROM python_migrations").fetchall()
        }
        for migration in sorted(migrations.glob("*.sql")):
            if migration.name in applied:
                continue
            raw = migration.read_text(encoding="utf-8")
            for statement in raw.split("-- statement"):
                sql = _migration_sql(statement.strip(), connection.dialect.name)
                if sql:
                    connection.exec_driver_sql(sql)
            if migration.name == "005_hash_legacy_conversation_tokens.sql":
                _hash_legacy_conversation_tokens(connection)
            connection.execute(
                text("INSERT INTO python_migrations (name) VALUES (:name)"),
                {"name": migration.name},
            )


def _hash_legacy_conversation_tokens(connection: Connection) -> None:
    rows = connection.execute(text("SELECT id,public_token FROM conversations")).mappings().all()
    for row in rows:
        token_hash = hashlib.sha256(str(row["public_token"]).encode()).hexdigest()
        connection.execute(
            text("UPDATE conversations SET public_token=:token_hash WHERE id=:id"),
            {"token_hash": token_hash, "id": row["id"]},
        )


def _migration_sql(sql: str, dialect: str) -> str:
    if dialect != "postgresql":
        return sql
    return (
        sql.replace(
            "INTEGER PRIMARY KEY AUTOINCREMENT",
            "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        )
        .replace("DATETIME", "TIMESTAMPTZ")
        .replace("BOOLEAN NOT NULL DEFAULT 1", "BOOLEAN NOT NULL DEFAULT TRUE")
        .replace("BOOLEAN NOT NULL DEFAULT 0", "BOOLEAN NOT NULL DEFAULT FALSE")
    )


def json_value(value: object, fallback: object) -> object:
    if value is None:
        return fallback
    if isinstance(value, dict | list):
        return value
    try:
        return json.loads(str(value))
    except (TypeError, ValueError, json.JSONDecodeError):
        return fallback
